# ===================================================================
# Spring Cloud Config bootstrap configuration for the "prod" profile
# ===================================================================

# Conditionally disable springdoc on missing api-docs profile
legacyServer:
  employee_url: https://apps.ccc.net/
  config: /config/keycloak-prod.json

spring:
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 100
      uri: http://admin:${jhipster.registry.password}@10.1.1.91:8761/config
      # name of the config server's property source (file.yml) that we want to use
      name: MaterialRequisition
      profile: prod # profile(s) of the property source
      label: main # toggle to switch to a different version of the configuration as stored in git
      # it can be set to any label, branch or commit of the configuration source Git repository

jhipster:
  registry:
    password: admin
